- name: Gather the package facts
  become: true
  package_facts:
    manager: auto

- name: Remove packages
  when: "'nvidia-docker' not in ansible_facts.packages and 'nvidia-docker2' not in ansible_facts.packages"
  apt:
    name:
      - nvidia-docker
      - nvidia-docker2
    state: absent
    autoremove: yes
    purge: yes

- name: Add key
  apt_key:
    url: "{{ nvidia_docker_repo_gpg_url }}"
    state: present
  when: "nvidia_docker_add_repo and 'nvidia-docker' not in ansible_facts.packages and 'nvidia-docker2' not in ansible_facts.packages"
  environment: "{{proxy_env if proxy_env is defined else {}}}"

- name: Add repo
  get_url:
    url: "{{ nvidia_docker_repo_base_url }}/{{ ansible_local['nv_os_release']['nv_os_release'] }}/{{ _ubuntu_repo_file_name }}"
    dest: "{{ _ubuntu_repo_file_path }}"
    mode: 0644
    owner: root
    group: root
  when: "nvidia_docker_add_repo and 'nvidia-docker' not in ansible_facts.packages and 'nvidia-docker2' not in ansible_facts.packages"
  environment: "{{proxy_env if proxy_env is defined else {}}}"

- name: Install packages
  when: "'nvidia-docker' not in ansible_facts.packages and 'nvidia-docker2' not in ansible_facts.packages"
  apt:
    name: 
      - nvidia-container-runtime
      - nvidia-docker2={{ nvidia_docker_version }}
    state: present
    update_cache: yes
  environment: "{{proxy_env if proxy_env is defined else {}}}"
